name: Package release
run-name: Release package "${{ github.event.head_commit.message }}"
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash -lieo pipefail {0}
on:
  push:
    branches:
      - "main"

jobs:
  publish-gpr:
    runs-on:
      [
        self-hosted,
        linux,
        ARM64,
        containered,
        "${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}",
      ]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: nvm install v20.10.0
      - run: nvm alias default v20.10.0
      - run: nvm use default
      - run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
